# Generated by Django 5.0.14 on 2025-05-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_checked',
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('need', 'Need'), ('will_buy', 'Will Buy'), ('bought', 'Bought')], default='need', max_length=10),
        ),
    ]
